### ISSUE TITLE
ModuleNotFoundError: No module named `'frontend'`

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-suite-docker#90]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Hello,

I want to report an issue getted when I tried to get the latest version of G3W (dev version).
When I try to start the project, in the starting phase of containers, the docker log show me this errors:

```log
Build started for G3W-Suite installation ...
Building javascript code ...
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning Ignored scripts due to flag.
[4/4] Building fresh packages...
Done in 92.22s.
Error: EEXIST: file already exists, symlink '/code/node_modules/@bower_components' -> 'g3w-admin/core/static/bower_components'
    at Object.symlinkSync (fs.js:1095:3)
    at [eval]:1:21
    at Script.runInThisContext (vm.js:120:18)
    at Object.runInThisContext (vm.js:309:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3 {
  errno: -17,
  syscall: 'symlink',
  code: 'EEXIST',
  path: '/code/node_modules/@bower_components',
  dest: 'g3w-admin/core/static/bower_components'
}
Setup started for G3W-Suite installation ...
Cleaning up some dirs before collecting statics ...
projects
/code /code
projects
/code
Creating projects(_data) directores in /shared-volume/media/projects ...
wait-for-it: waiting 60 seconds for postgis:5432
wait-for-it: postgis:5432 is available after 0 seconds
/code /code
/code
Traceback (most recent call last):
  File "/code/g3w-admin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'frontend'
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'frontend'
```

I don't have any issues on postgis container, I detect this issu only to g3w-suite-1 container.

Suggestions?

Thank's in advance

### Steps to reproduce

Starting of project refers to dev version

### Environment

- g3w-admin: 3.5-dev
- g3w-client: 3.7-dev
- browser: chrome
- operating system: windows 10

**Comment by volterra79** [comment]
@bard0x [in this bug tracker the language to use is English, adapt to this standard if you are looking for help from other users](https://github.com/g3w-suite/g3w-admin/issues/432#issuecomment-1363773755)

**Comment by bard0x** [comment]
> @bard0x [in this bug tracker the language to use is English, adapt to this standard if you are looking for help from other users](https://github.com/g3w-suite/g3w-admin/issues/432#issuecomment-1363773755)

Hi,

I translated the issue above. Thank's for the info

**Comment by Raruto** [comment]
> I translated the issue above.

Thanks @bard0x, and please in future also remember to always report the exact software versions (ie. g3w-suite: `v3.5`, ...) on which you are having trouble (otherwise it can become very difficult to help you, specifying just `dev` version is not a fixed and stable version over time..)

---

> ModuleNotFoundError: No module named 'frontend

Temporarily you can revert the changes from this commit to make it work again: https://github.com/g3w-suite/g3w-suite-docker/commit/9475d8260979309e9e583a951306326b016247ea

---

For the record, I move this under the [g3w-suite-docker](https://github.com/g3w-suite/g3w-suite-docker) repo  

_Have a nice day,
Raruto_

**Comment by NyakudyaA** [comment]
i think this can be closed

**Comment by Raruto** [comment]
> i think this can be closed

@NyakudyaA am i missing something?

I still get the same error when trying on a clean install:

![image](https://user-images.githubusercontent.com/9614886/226852546-5fde9f2d-3962-431c-97ba-66dad214bc3f.png)

👋 Raruto
