### ISSUE TITLE
No module named `'django_redis'` after v3.5.x

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-suite-docker#98]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Hi,

I tried to update to the latest version of g3w but in start phase of containers I have this error:

```
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': No module named 'django_redis'
```

Why this occurs?

Thanks in advance for the reply.

bard0x

### Steps to reproduce

Update g3w-admin & g3w-client & g3w-suite-docker to the latest version pushed on git

### Environment

- g3w-admin: v3.6.0-alpha.0
- g3w-client: v3.8.0-beta.0
- browser: chrome 
- operating system: windows10

**Comment by wlorenzetti** [comment]
@bard0x how to update? Did you create new docker image?

**Comment by bard0x** [comment]
> @bard0x how to update? Did you create new docker image?

Yes, I recloned from git every project (client, admin & suite-docker)... Like a new installation

**Comment by wlorenzetti** [comment]
And after did you recreate the *g3wsuite/g3w-suite:dev* image?

**Comment by bard0x** [comment]
> And after did you recreate the _g3wsuite/g3w-suite:dev_ image?

Yes, exactly

**Comment by wlorenzetti** [comment]
It's very strange inside `requirements.txt` is set https://github.com/g3w-suite/g3w-admin/blob/b61ac04d76f8589d2b02039ee70af576e1a0e8be/requirements.txt#L39

So on new build It could be installed inside the image.

**Comment by bard0x** [comment]
> It's very strange inside `requirements.txt` is set
> 
> https://github.com/g3w-suite/g3w-admin/blob/b61ac04d76f8589d2b02039ee70af576e1a0e8be/requirements.txt#L39
> 
> So on new build It could be installed inside the image.

Yes, I find it too on the requirements.txt but don't works :(

**Comment by wlorenzetti** [comment]
I just make a test. I build the image in this way:
```
docker build -f Dockerfile.g3wsuite.dockerfile --build-arg G3W_SUITE_BRANCH=v3.6.0-alpha.0 -t g3wsuite/g3w-suite:dev --no-cache .
```
Using branch dev of g3wsuite/g3w-suite-dockder repository, but all work fine:(.

**Comment by bard0x** [comment]
> I just make a test. I build the image in this way:
> 
> ```
> docker build -f Dockerfile.g3wsuite.dockerfile --build-arg G3W_SUITE_BRANCH=v3.6.0-alpha.0 -t g3wsuite/g3w-suite:dev --no-cache .
> ```
> 
> Using branch dev of g3wsuite/g3w-suite-dockder repository, but all work fine:(.

I tried to install manually entering this command by bash into docker container...

```sh
root@d998c553dba9:/code# pip install django-redis

Collecting django-redis
  Downloading django_redis-5.2.0-py3-none-any.whl (30 kB)
Requirement already satisfied: Django>=2.2 in /usr/local/lib/python3.10/dist-packages (from django-redis) (2.2.28)
Requirement already satisfied: redis!=4.0.0,!=4.0.1,>=3 in /usr/local/lib/python3.10/dist-packages (from django-redis) (4.5.4)
Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from Django>=2.2->django-redis) (0.4.3)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from Django>=2.2->django-redis) (2022.1)
Requirement already satisfied: async-timeout>=4.0.2 in /usr/local/lib/python3.10/dist-packages (from redis!=4.0.0,!=4.0.1,>=3->django-redis) (4.0.2)

Installing collected packages: django-redis
Successfully installed django-redis-5.2.0

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```


After this command I have these new errors:

```sh
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/liblandingpage.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"

Exception in thread django-main-thread:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_permission" does not exist
LINE 1: ...ntent_type_id", "auth_permission"."codename" FROM "auth_perm...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 387, in check
    all_issues = self._run_checks(
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 403, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/g3w-admin/base/urls.py", line 173, in <module>
    include('{}.urls'.format(app))
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/g3w-admin/qdjango/urls.py", line 15, in <module>
    from .sitetrees import sitetrees
  File "/code/g3w-admin/qdjango/sitetrees.py", line 16, in <module>

(
  File "/usr/local/lib/python3.10/dist-packages/sitetree/utils.py", line 119, in item
    perm = Permission.objects.get(codename=codename, content_type__app_label=app)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_permission" does not exist
LINE 1: ...ntent_type_id", "auth_permission"."codename" FROM "auth_perm...
                                                             ^

```

**Comment by Raruto** [comment]
> psycopg2.errors.UndefinedTable: relation "auth_permission" does not exist

@bard0x you probably have to apply some [migrations](https://docs.djangoproject.com/en/3.2/topics/migrations/), delete these files `/shared-volume/setup_done` and `/shared-volume/build_done` and then try again.

**For more info:** 

- https://github.com/g3w-suite/g3w-suite-docker/blob/e9ed3cd6d6b6b9af3e0cad0f2642c8f54dae09e7/scripts/docker-entrypoint-dev.sh#L15-L18
- [g3w-admin/ci_scripts/build_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/fb58feaaea39457bc38504b10f06c31995df22fe/ci_scripts/build_suite.sh)
- [g3w-admin/ci_scripts/setup_suite.sh](https://github.com/g3w-suite/g3w-admin/blob/fb58feaaea39457bc38504b10f06c31995df22fe/ci_scripts/setup_suite.sh)

👋 Raruto

**Comment by fpuga** [comment]
I try to run the project in my local computer.

```
git clone https://github.com/g3w-suite/g3w-suite-docker.git
cd g3w-suite-docker
git checkout -b v3.6.x
cp .env.example .env
docker compose up -d
```

Opening localhost:8080 i get a bad gateway error. The only problem I found in the logs is the same reported here:

> django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': No module named 'django_redis'

I also try with dev branch, and in v3.6.x branch changing the g3w-suite image tag from dev to v3.6.x, but I still getting this error.

**Comment by fpuga** [comment]
Sorry I make a mistake in one of my tests. This works:

```
git clone https://github.com/g3w-suite/g3w-suite-docker.git
cd g3w-suite-docker
git checkout -b v3.6.x
cp .env.example .env
# edit docker-compose.yml and change "image: g3wsuite/g3w-suite:dev" with "image: g3wsuite/g3w-suite:v3.6.x"

docker compose up -d
```

With this change it works.

In docker hub repo https://hub.docker.com/r/g3wsuite/g3w-suite/tags the dev tag image have not been updated from 5 months ago.

So I think that dev image should be updated. And also I think it will be a good idea match the git tag version with the image version.

**Comment by wlorenzetti** [comment]
Hi @fpuga  @bard0x  I just test with v3.6.x branch and all work fine. 

> In docker hub repo https://hub.docker.com/r/g3wsuite/g3w-suite/tags the dev tag image have not been updated from 5 months ago.

> So I think that dev image should be updated. And also I think it will be a good idea match the git tag version with the image version.

Yes sorry we are finding the right way to keep updated the dev image on docker-hub. I suggest to build the image on your machine to get the latest code version.

**Comment by Raruto** [comment]
@bard0x @fpuga is this still a problem?

Please let us know if we can close this.

By the way, [**v3.7**](https://github.com/g3w-suite/g3w-admin/milestone/8) will be out soon ☄️ 

👋 Raruto

**Comment by fpuga** [comment]
Sorry for the late answer. It can be closed. Cheers.
